version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: "3.9"
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  formats:
    - htmlzip
    - pdf
    - epub

branches:
  - main
  - master
  - /release/
  - /v\d+\.\d+\.\d+/

tags:
  - /v\d+\.\d+\.\d+/
